### ISSUE TITLE
sandbox linux

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscale_prefab#21]
## goals

- [x] need autobuild in prefab on zero-os (starting from the ubuntu 18.04 flist)
- [ ] sandbox using js95 and upload to local zdb using zero-flist library/python bindings
- [ ] test the sandbox using zero-os (launch container with sandbox, see if it works using ssh) for both methods
- [ ] example script which drives all of this (hosted in sandbox dir of this repo)
- [ ] test the sandbox using the zbundle tool on empty ubuntu (18.04 as container in ZOS)
- [ ] documentation properly done
- [x] all lib's (pip) as used for lib9, core9, prefab, digitalme all installed
- [x] use official install methods from 9.5 inside ubuntu 18.04 in ZOS over prefab
- [ ] has jumpcale inside  (without .git parts)
- [x] has env.sh script which sets required env variables
- [ ] python std libs (without .so ones) in .zip file so it goes much faster to load
- [ ] update script for jumpscale95 which get's newest git code & expand over existing dir's

## remarks

- learn from how we did it in: https://github.com/Jumpscale/sandbox_osx
- https://github.com/threefoldtech/jumpscale_prefab/tree/development/sandboxers need to host code/examples
- local zdb: local can be developer machine or zos

**Comment by zaibon** [comment]
can't figure out the current sandboxing code at all. this is way to messy. the guy that wrote this should probably adapt it to fit this requirements and when we have time should clean this all thing up

**Comment by despiegk** [comment]
continues in https://github.com/threefoldtech/jumpscale_lib/issues/92
