### ISSUE TITLE
Test prefab methods 

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/jumpscale_prefab#27]
We need to test all the prefab methods with the happy scenarios.

**What should be tested?**
- Docs for each method
- Happy path scenario is working well for each method

**What should u deliver?** 
- We expect a google drive sheet with `method_name`, `testing variables`, `test result`, `error message` as its header.

**Comment by ahussein** [comment]
I think we (internally) talked about this before and thought that the best approach is to implement a test method on each prefab module. This way each prefab would implement a appropriate tests that are needed and a test runner would just call the test method of all the prefab if they exist.

**Comment by Dina-Abd-Elrahman** [comment]
## Version:

- core: 71ed31ee5acc828f128fdb9bdedbebe09e08a40b
- lib: 1c8d6a983d1062b722ec54c50b319a272255926a
- prefab: 502ffd7ede891012799a5ae87043291a761d09d0

https://docs.google.com/spreadsheets/d/1RkmH4ErT9u85uEooVPca_nP7PU_jL_qAKgsbDqf2Ysw/edit#gid=1913967487

**Comment by despiegk** [comment]
see

**Comment by despiegk** [comment]
https://github.com/threefoldtech/jumpscale_prefab/issues/40
