### ISSUE TITLE
prefab methods issues

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscale_prefab#30]
#### Detailed description

you can find prefab methods issues in the following link:

https://docs.google.com/spreadsheets/d/1RkmH4ErT9u85uEooVPca_nP7PU_jL_qAKgsbDqf2Ysw/edit#gid=1913967487

#### Installation information

- jumpscale version: 
core: 617a7ad5a767f1fd7fb7a2a5d6a8cc9c112009e8
lib: bc1fe0b4e3bf9d3a650cbb3b8e090fbcea523a9f
prefab: 7eab488e38abb629eb230d6e5327eb1b58894eeb

- operating system:
Ubuntu 16.04

**Comment by despiegk** [comment]
see https://github.com/threefoldtech/jumpscale_prefab/issues/40
