### ISSUE TITLE
Can't access Ubuntu VM created on ZOS (using flist) when using "mount"

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscale_prefab#31]
### Steps:
 Create VM on ZOS using 0-core Client:
```
name = 'ahmed'
flist = 'https://hub.grid.tf/tf-bootable/ubuntu:latest.flist'
nics = [{'type': 'default'}]
port = {24:22}
config = {'/root/.ssh/authorized_keys': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDrxj7aUpIFrrmMoKqf07z0k6GY5mt/42ND8cBU1h1PED2L3pZAEWaViQPhHsP77XKQo2W9+TD4BIai65m9Ib4jZy5zbCSIDMlL9ukRaWKuC4QcFl2+Ge2nH1imrn9ZYy2pPMwNvES17Fo9xZIWI8R5KFyZpAsrL5Je1AWFi3aTbtHqPwAKDzyiyqekh8yyMehmRsi3wm17F6M0PJ4r5mlfkCycIMRR3W62UoQM2eQjYKVa1gqN3ZeLrRClmBrF7mIXOzJywdX1tfh+ayZ36F2fFUcm6G8X/xpfQpFbEDds/ohcwvMbYR6JYxC/Ugn4KSeTXk4534wAVtS9xpXDX9oR ahmed@ahmed-HP-ProBook-450-G1'}
mount = [{'source': '/ahmed', 'target': 'share', 'readonly': False}]
client.kvm.create(name=name, flist=flist, nics=nics, port=port, config=config, mount=mount)
```
### Issue:
The VM created with default network but I couldn't access the VM using (ssh).

#### Predictable Network Interface Names 
when I used 'mount', it added new PCI interface and took name (ensX) which result in the default network interface name changed.
If I don't use mount, I can access it using (ssh).

#### To solve:
This problem should be handled on the build code of Ubuntu flist ([PrefabUbuntu.py](https://github.com/threefoldtech/jumpscale_prefab/blob/development/modules/os/PrefabUbuntu.py)) or disable it and go back to unpredictable kernel-native (ethX) naming.

**Comment by john-kheir** [comment]
https://github.com/threefoldtech/0-core/pull/135/commits/02093b3bc0a874a099a66946e8043a6f74c4ba8e
