### ISSUE TITLE
An atomic swap install should not automatically build

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/jumpscale_prefab#37]
Rob Van Mieghem, [11 Oct 2018 at 10:56:20]:
we have the atomic swap go project

that also has releases on github

the current atomicswap prefab install installs go , then fetches the sources, builds and installs

is that the correct flow or should an install just fetch the binaries from github ?

and maybe check if a local build exists first before doing that

Reem Khamis, [11 Oct 2018 at 10:59:29]:
in the build method, usually we build from scratch. Which is used mainly for sandboxing, meaning you ensure that golang is installed on the machine and builds the binaries. Install can do indeed fetching from the repo if local build doesn't exist

**Comment by despiegk** [comment]
in prefab its always building then we go to flists & we deploy
